# 🧩 Day 1 Practice — 15 Questions (up to Slicing)

**Topics covered:** array creation · `dtype` / `astype` · attributes · indexing · slicing · boolean indexing
**Level:** Medium · **Rule:** solve using only these topics — no loops!

**Q1.** Create an array of the first 12 **odd numbers** using a single **np.arange** call.

**Q2.** Using **np.linspace**, create 9 equally spaced values from 5 to 45. Before running, **predict the gap** between consecutive values - then verify.

**Q3.** Create **np.arange(1, 10)** and **np.linspace(1, 9, 9)**. Print both and compare their **dtype**. Why are they different?

**Q4.** Create a **6x6 identity matrix** with integer dtype - the output must show no decimal points.

**Q5.** Create a **3x4 matrix** where every element is **5**, and report its shape, size, and ndim.

**Q6.** Given **a = np.array([2, 4, 6])** and **b = np.array([2.0, 4.0, 6.0])** - check both dtypes, then convert b to int with **astype** and verify the dtypes now match.

**Q7.** **Predict the exact output** of **np.array([10.9, 25.5, 39.99]).astype(int)** before running it. What rule does the result prove?

**Q8.** Given **arr = np.arange(10, 101, 10)** - extract: (a) the 4th element, (b) the last element using negative indexing, (c) the 2nd-last element.

**Q9.** From the same arr, slice out exactly **[30 40 50 60]**, and separately produce the **full array in reverse**.

**Q10.** Given **arr = np.arange(1, 21)** - extract **every 3rd element starting from index 1** (result: 2, 5, 8, ...).

**Q11.** Using **one slice only**, extract everything from arr (1-20) EXCEPT the first two and the last two elements.

**Q12.** Using the matrix below, extract: (a) the **3rd row**, (b) the **last column**, (c) the **centre 3x3 block**.
```python
m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])
```

**Q13.** From the same matrix, extract the **four corner elements** as a 2x2 array - using **step slicing only**.

**Q14.** From the same matrix, extract **every alternate row AND every alternate column** at the same time (the result is 3x3).

**Q15.** Given the marks array below - (a) extract all marks **greater than 60**; (b) extract marks **between 50 and 80** using two conditions with & (remember the parentheses!).
```python
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])
```

In [1]:
# Q1
import numpy as np
arr = np.arange(1,24,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23]


In [ ]:
# Q2
print(np.linspace(5,45,9))  #gap is calculated using the formula (end-start)/(number of values-1)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]


In [ ]:
# Q3
arr1 = np.arange(1,10)
arr2 = np.linspace(1,9,9)
print(arr1)
print("dtype of arr1 =",arr1.dtype) #.dtype
print(arr2)
print("dtype of arr2 =",arr2.dtype) #.dtype 

#linspace is designed to create an array with evenly spaced values, which may not be integers, so by default it returns values in float64, even if spacing gives integers as output 

[1 2 3 4 5 6 7 8 9]
dtype of arr1 = int64
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
dtype of arr2 = float64


In [ ]:
# Q4
# USE np.eye for creating IDENTITY MATRIX np.eye(rows,columns,k=where to start 1 from)
print(np.eye(6,6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
# Q5
x = np.full((3,4),5) #np.zeros  | np.ones  | np.full((row,column),fill with digit)
print(x)
print("Shape =",x.shape) #(rows,columns)
print("Size =",x.size) #total elements = rows*columns
print("ndim =",x.ndim) #number of dimensions

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Shape = (3, 4)
Size = 12
ndim = 2


In [ ]:
# Q6
a = np.array([2,4,6])
b = np.array([2.0,4.0,6.0])
print("a's dtype =",a.dtype,"& b's dtype =",b.dtype)
b = b.astype(int) #converted b's dtype using astype
print("b's dtype =",b.dtype)

a's dtype = int64 & b's dtype = float64
b's dtype = int64


In [ ]:
# Q7
arr3 = np.array([10.9,25.5,39.99]).astype(int)
print(arr3.dtype)
print(arr3)

#the result prpves that it is not using the round-off concept and simply ignoring the the value after decimal

int64
[10 25 39]


In [ ]:
# Q8
arr4 = np.arange(10,101,10)
print(arr4)
print(arr4[3]) #4th element is at 3rd index
print(arr4[-1]) #last element using negative indexing
print(arr4[-2]) #2nd last element

[ 10  20  30  40  50  60  70  80  90 100]
40
90


In [ ]:
# Q9
print(arr4[2:5]) #specific part of the array
print(arr4[::-1]) #reversed array

[30 40 50]
[100  90  80  70  60  50  40  30  20  10]


In [ ]:
# Q10
arr5 = np.arange(1,21)
print(arr5)
print(arr5[1::3]) #every 3rd element

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 2  5  8 11 14 17 20]


In [ ]:
# Q11
print(arr5[2:17]) 

#removing first two elements - start from index 2
#remving last two elements - travel till len(arr5)-3 

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [ ]:
m = np.array([[ 1,  2,  3,  4,  5],
              [ 6,  7,  8,  9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])

print(m[2:3,::]) #extracted the 3rd row
print(m[::,4]) #extracted the last column
print(m[1:4,1:4]) #extracted the centre 3x3 block


[[11 12 13 14 15]]
[ 5 10 15 20 25]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
# Q13
print(m[3:,3:]) #extracted the four corner elements

[[19 20]
 [24 25]]


In [ ]:
# Q14
print(m[::2,::2]) #extracted alternate rows and columns

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [56]:
# Q15
marks = np.array([56, 91, 44, 77, 62, 85, 39, 70])

print(marks[marks>60])
print(marks[(marks>50) & (marks<80)])

[91 77 62 85 70]
[56 77 62 70]


---
✅ **Done?** Cross-check every slicing answer by predicting the output *before* running the cell — that habit is what builds real logic.