In [1]:
import numpy as np

In [8]:
s1 = np.array([72, 85, 60, 91])
s2 = np.array([45, 30, 98, 55])
s3 = np.array([88, 66, 74, 100])

old = np.array([
    [62, 71, 55, 80],
    [49, 58, 66, 73]
])

# quetsion 1
table = np.array([s1, s2, s3])

print("Main table:")
print(table)


#  quetion 2
students, subjects = table.shape

print("Number of students:", students)
print("Number of subjects:", subjects)

# question 3
print("Total marks entries:", table.size)


#  question 4
ans = table.astype(float)
print("ans :")
print(ans)

# quetion 5
old = old.astype(int)

old_total = np.sum(old, axis=1)

print("Total marks of old students:")
print(old_total)


# quetsion 6
final_table = np.vstack((table, old))

print("Final table:")
print(final_table)


Main table:
[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
Number of students: 3
Number of subjects: 4
Total marks entries: 12
ans :
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
Total marks of old students:
[268 246]
Final table:
[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]
